=== cefn/lowban/schema/db.schema.json
{
  "$id": "https://github.com/cefn/lowban/schema/db.schema.js",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "categoryTagIdPattern": {
      "type": "string",
      "pattern": "^[a-zA-Z\\d\\s:\\u00C0-\\u00FF].*$"
    },
    "priorityTagIdPattern": {
      "type": "string",
      "pattern": "^!.*$"
    },
    "contextTagIdPattern": {
      "type": "string",
      "pattern": "^@.*$"
    },
    "statusTagIdPattern": {
      "type": "string",
      "pattern": "^#.*$"
    }
  },
  "properties": {
    "task": {
      "type": "array",
      "items": {
        "$ref": "./task.schema.json#/definitions/task"
      }
    },
    "category": {
      "type": "array",
      "items": {
        "allOf": [
          { "$ref": "./tag.schema.json#/definitions/tag" },
          {
            "properties": {
              "id": {
                "$ref": "#/definitions/categoryTagIdPattern"
              }
            }
          }
        ]
      }
    },
    "priority": {
      "type": "array",
      "items": {
        "allOf": [
          { "$ref": "./tag.schema.json#/definitions/tag" },
          {
            "properties": {
              "id": {
                "$ref": "#/definitions/priorityTagIdPattern"
              }
            }
          }
        ]
      }
    },
    "context": {
      "type": "array",
      "items": {
        "allOf": [
          { "$ref": "./tag.schema.json#/definitions/tag" },
          {
            "properties": {
              "id": {
                "$ref": "#/definitions/contextTagIdPattern"
              }
            }
          }
        ]
      }
    },
    "status": {
      "type": "array",
      "items": {
        "allOf": [
          { "$ref": "./tag.schema.json#/definitions/tag" },
          {
            "properties": {
              "id": {
                "$ref": "#/definitions/statusTagIdPattern"
              }
            }
          }
        ]
      }
    }
  }
}

=== cefn/lowban/examples/moon.db.json
{
  "task": [
    {
      "id": "0",
      "label": "Fuel Rocket",
      "text": "The rocket consists of three stages—the S-IC first stage, S-II second stage and the S-IVB third stage—and the instrument unit. All three stages use liquid oxygen (LOX) as the oxidizer. The first stage uses RP-1 for fuel, while the second and third stages use liquid hydrogen (LH2)",
      "tagIds": ["@earth", "!mustdo"]
    },
    {
      "id": "1",
      "label": "Landing Quote",
      "text": "Say something witty when you are on the moon",
      "tagIds": ["@moon", "wishlist", "fun"]
    }
  ],
  "category": [{ "id": "fun" }],
  "priority": [{ "id": "!mustdo" }, { "id": "!wishlist" }],
  "context": [
    { "id": "@earth" },
    { "id": "@rocket" },
    { "id": "@orbit" },
    { "id": "@lander" },
    { "id": "@moon" }
  ],
  "status": [{ "id": "#waiting" }, { "id": "#done" }]
}
